import {Dimensions} from 'react-native';

export enum FONTS {
  regular = 'Manrope-Regular',
  medium = 'Manrope-Medium',
  bold = 'Manrope-Bold',
  semiBold = 'Manrope-SemiBold',
  light = 'Manrope-Light',
  extraLight = 'Manrope-ExtraLight',
  extraBold = 'Manrope-ExtraBold',
}

const {height, width} = Dimensions.get('window');

export const COLORS = {
  PRIMARY: '#1F4B28',
  PRIMARY_DARK: '#13361A',
  PRIMARY_LIGHT: '#2B5D32',

  BACKGROUND: '#F7F9F7',
  SURFACE: '#FFFFFF',

  TEXT: '#18231B',
  TEXT_SECONDARY: '#6B826D',
  TEXT_MUTED: '#9DA89F',

  BORDER: '#DADCDA',
  BORDER_LIGHT: '#E8EAE8',

  SUCCESS: '#2B5D32',
  NOTIFICATION_ACCENT: '#D3B351',

  HEADER_TEXT_MUTED: '#93AD98',
  HEADER_BORDER: 'rgba(255,255,255,0.28)',
  HEADER_DIVIDER: 'rgba(255,255,255,0.22)',

  INVOICE_BORDER: '#E2E7E3',
  INVOICE_SHADOW: '#17371D',
  INVOICE_AVATAR_BACKGROUND: '#EDF4EF',
  INVOICE_AVATAR_TEXT: '#3C7448',
  INVOICE_PAID_BACKGROUND: '#E4F2E6',
  INVOICE_PAID_TEXT: '#4D8659',
  INVOICE_DRAFT_BACKGROUND: '#FFF1CD',
  INVOICE_DRAFT_TEXT: '#B48A2D',
  INVOICE_DUE_TEXT: '#D46D58',

  MENU_ICON_MUTED: '#98A99B',
  MENU_PREVIEW_BORDER: '#D8E0DA',
  MENU_GREEN_BACKGROUND: '#F0F6F1',
  MENU_GREEN_ACCENT: '#3C7448',
  MENU_GREEN_LINES: '#C8D7CB',
  MENU_MINIMAL_BACKGROUND: '#F6F6F5',
  MENU_MINIMAL_ACCENT: '#303433',
  MENU_MINIMAL_LINES: '#D4D7D5',
  MENU_HERITAGE_BACKGROUND: '#FFF4EA',
  MENU_HERITAGE_ACCENT: '#8C2617',
  MENU_HERITAGE_LINES: '#E7C3A6',

  LOGIN_BACKGROUND: '#FFFFFF',
  LOGIN_PRIMARY: '#397D2D',
  LOGIN_SEGMENT_BACKGROUND: '#F5F6F9',
  LOGIN_TEXT: '#6D6D6D',
  LOGIN_INPUT_BORDER: '#C9C9C9',
  LOGIN_ICON: '#898989',
  LOGIN_DIVIDER: '#E1E1E1',

  WHITE: '#FFFFFF',
  LIGHT_GREY_BG: '#FFFFFF',
  GREYSCALE_50: '#FFFFFF',
  GREYSCALE_100: '#F5F6F9',
  GREYSCALE_200: '#E1E1E1',
  GREYSCALE_500: '#898989',
  GREYSCALE_700: '#6D6D6D',
  GREYSCALE_900: '#1F1F1F',
  GRAY_TEXT: '#6D6D6D',
  RED_ERROR: '#D14343',
  BUTTON_DISABLE: '#AEBEAA',

  TOAST_SUCCESS_BACKGROUND: '#EDF4EF',
  TOAST_SUCCESS_BORDER: '#397D2D',
  TOAST_SUCCESS_TEXT: '#1F4B28',
  TOAST_ERROR_BACKGROUND: '#FDEDEC',
  TOAST_ERROR_BORDER: '#D14343',
  TOAST_ERROR_TEXT: '#9F2F2F',

  OTP_INPUT_BORDER: '#DEDEDE',
  OTP_DISABLED_BACKGROUND: '#E2E2E2',
  OTP_DISABLED_TEXT: '#B7B7B7',

  SKELETON_BONE: '#E2E9E3',
  SKELETON_HIGHLIGHT: '#F4F7F4',

  INVOICE_FORM_BACKGROUND: '#F5F7F5',
  INVOICE_FORM_FIELD_BORDER: '#D7DDD8',
  INVOICE_FORM_MUTED: '#F4F5F6',
  INVOICE_FORM_BADGE: '#E7F2E8',
  INVOICE_FORM_BADGE_TEXT: '#4D8659',
  INVOICE_DELETE: '#D83A4A',
};

export const FONT_SIZE = {
  SM: 12,
  MD: 16,
  LG: 20,
};

export const SCREEN_PADDING = 20;

export const SCREEN = {
  HEIGHT: height,
  WIDTH: width,
};
