export const DUMMY_PROPERTY_IMAGE =
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80';

export const STATIC_PROPERTY_DETAIL = {
  id: '05419823-71e6-4ef5-8182-cedec365ff9b',
  title: 'The Boonies- Duplex Villa with Jacuzzi',
  description:
    'Nestled in serene apple orchards, this charming duplex villa offers breathtaking views of snow-capped mountains. Designed with a wooden roof and staircase, it features two skylights that fill the interiors with sunlight and showcase stunning night skies.\n\nThe villa accommodates 5-8 guests, making it ideal for families seeking tranquility. In winter, it transforms into a snowy haven, perfect for relaxing and enjoying peaceful moments in nature\'s embrace.\n\nThe space\nThis duplex villa is fully equipped for comfort and convenience, catering to all your needs. With two rooms and two bathrooms, each room is bathed in natural light and offers breathtaking views of the mountains from every corner. Enjoy the peace and beauty through large windows, and stargaze through skylights at night.\n\nThe entire villa consists of three rooms in total. Two rooms are interconnected with one common main door, and the third is a private room with an independent entrance from the ground floor.\n\nFor those looking to stay productive, the villa includes a dedicated work desk and chair with panoramic mountain views, providing the perfect setting to get your creative juices flowing.\n\nThe villa is thoughtfully designed with all the needful amenities to ensure a comfortable stay. We also provide board games for family time and various activities to keep children entertained. Room service and housekeeping are available on request, ensuring your privacy and peace throughout your stay.\n\nNote: Property is around 6-7 km from main Narkanda market and last 200 meter road is unmetalled or kacha road.\n\nJacuzzi Note: Hot water for the jacuzzi is provided through a solar geyser (200+ liter capacity) and depends entirely on sunlight. Hence, we do not recommend using the jacuzzi during cloudy or rainy weather. In winter, the best time to use the jacuzzi is in the afternoon.',
  propertyType: 'shared_room',
  totalBedrooms: 2,
  totalBathrooms: 2,
  maxGuests: 5,
  city: 'Narkanda',
  state: 'Himachal Pradesh',
  isPet: true,
  dummyImageUrl: DUMMY_PROPERTY_IMAGE,
  googleReviews: {
    GoogleRating: 4.7,
    TotalReviews: 43,
  },
  cancellationPolicy: {
    name: 'Flexible',
    description: 'Full refund if cancelled 7 days before check-in',
  },
  listingQuestions: [
    {
      id: 'distance_from_main_town',
      icon: 'LocationOnIcon',
      enabled: true,
      question: 'Distance from Bus Stand / Main Town',
      answer: '7',
      distanceType: 'km',
    },
    {
      id: 'off_road',
      icon: 'TerrainIcon',
      enabled: true,
      question: 'Off-road / Kacha Road',
      booleanAnswer: true,
      distanceType: 'm',
      subQuestion: {
        answer: '200',
      },
    },
    {
      id: 'walking_distance_from_parking',
      icon: 'DirectionsWalkIcon',
      enabled: true,
      question: 'Walking Distance from Parking',
      answer: '50',
      distanceType: 'm',
    },
    {
      id: 'parking',
      icon: 'LocalParking',
      enabled: true,
      question: 'Parking',
      booleanAnswer: false,
    },
    {
      id: 'stairs_access',
      icon: 'SignpostIcon',
      enabled: true,
      question: 'Stair climb required',
      booleanAnswer: true,
    },
    {
      id: 'suitable_for',
      icon: 'GroupIcon',
      enabled: true,
      question: 'Suitable For',
      selectedOptions: ['Couples', 'Families', 'Group of Friends'],
    },
  ],
  amenities: [
    {name: 'Iron', icon: 'iron'},
    {name: 'Microwave', icon: 'microwave'},
    {name: 'TV', icon: 'tv'},
    {name: 'Wardrobe', icon: 'checkroom'},
    {name: 'Towels', icon: 'dry_cleaning'},
    {name: 'Toiletries', icon: 'soap'},
    {name: 'Smoking Allowed', icon: 'smoking-rooms'},
    {name: 'Fire Extinguisher', icon: 'local-fire-department'},
    {name: 'Heating', icon: 'thermostat'},
    {name: 'Dining Area', icon: 'dining'},
    {name: 'Parking', icon: 'local_parking'},
    {name: 'Room Service', icon: 'room_service'},
    {name: 'First Aid Kit', icon: 'medical_services'},
    {name: 'Bed Linens', icon: 'bed'},
    {name: 'Washing Machine', icon: 'local_laundry_service'},
    {name: 'Wi-Fi', icon: 'wifi'},
    {name: 'Refrigerator', icon: 'kitchen'},
    {name: 'Hot/Cold Water', icon: 'water_drop'},
    {name: 'Pet Friendly', icon: 'pets'},
    {name: 'Meals Available', icon: 'restaurant'},
    {name: 'Board Games', icon: 'casino'},
    {name: 'Air Conditioning', icon: 'ac_unit'},
    {name: 'Smoke Detector', icon: 'smoke_free'},
    {name: 'Kettle', icon: 'electric_kettle'},
    {name: 'Balcony', icon: 'balcony'},
    {name: 'Garden', icon: 'yard'},
    {name: 'Cable TV', icon: 'cable'},
  ],
  host: {
    firstName: 'Praveen',
    lastName: 'Sharma',
    isVerified: true,
    avatar: null,
    languages: ['English', 'Hindi'],
    tagline: 'Your trusted local host — here to make your stay seamless.',
  },
  reviews: {
    pending: [],
    published: [],
    averageRating: null,
  },
};
