import {StyleSheet} from 'react-native';
import {COLORS, FONTS} from '../../../constants';

export default StyleSheet.create({
  screen: {
    backgroundColor: COLORS.BACKGROUND,
    flex: 1,
  },
  header: {
    backgroundColor: COLORS.PRIMARY_DARK,
    paddingBottom: 60,
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  brandRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  brand: {
    color: COLORS.SURFACE,
    fontFamily: FONTS.extraBold,
    fontSize: 15,
    letterSpacing: 3,
  },
  tagline: {
    color: '#84A98B',
    fontFamily: FONTS.bold,
    fontSize: 7,
    letterSpacing: 2,
    marginTop: 2,
  },
  notification: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  date: {
    marginTop: 15,
  },
  greeting: {
    marginTop: 4,
  },
  body: {
    flex: 1,
    marginTop: -43,
  },
  content: {
    paddingBottom: 90,
    paddingHorizontal: 14,
  },
  invoiceCard: {
    alignItems: 'center',
    backgroundColor: COLORS.SURFACE,
    borderColor: COLORS.BORDER_LIGHT,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 69,
    paddingHorizontal: 13,
    shadowColor: '#152B1A',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 3,
  },
  invoiceIcon: {
    alignItems: 'center',
    backgroundColor: COLORS.SUCCESS,
    borderRadius: 10,
    height: 41,
    justifyContent: 'center',
    width: 41,
  },
  invoiceCopy: {
    flex: 1,
    marginLeft: 11,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  quickAction: {
    backgroundColor: COLORS.SURFACE,
    borderColor: COLORS.BORDER_LIGHT,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    height: 75,
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#152B1A',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  quickIcon: {
    alignItems: 'center',
    backgroundColor: '#EDF4EF',
    borderRadius: 10,
    height: 31,
    justifyContent: 'center',
    marginBottom: 7,
    width: 31,
  },
  stats: {
    backgroundColor: COLORS.SURFACE,
    borderColor: COLORS.BORDER_LIGHT,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 14,
    overflow: 'hidden',
  },
  stat: {
    flex: 1,
    paddingHorizontal: 11,
    paddingVertical: 13,
  },
  statBorder: {
    borderLeftColor: COLORS.BORDER_LIGHT,
    borderLeftWidth: 1,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 16,
  },
  propertyList: {
    gap: 10,
    paddingRight: 14,
  },
  statsSkeletonContainer: {
    width: '100%',
  },
  propertiesSkeletonContainer: {
    overflow: 'hidden',
    width: '100%',
  },
  emptyProperties: {
    alignItems: 'center',
    backgroundColor: COLORS.SURFACE,
    borderColor: COLORS.BORDER_LIGHT,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 100,
    width: '100%',
  },
});
